# Generated by Django 2.2.4 on 2019-08-29 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaraj_builder', '0009_auto_20190829_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='quest',
            name='enquiry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 29, 22, 48, 56, 698448)),
        ),
        migrations.AlterField(
            model_name='quest',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='quest',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='entry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 29, 22, 48, 56, 698950)),
        ),
    ]
