# Generated by Django 2.2.4 on 2019-08-31 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaraj_builder', '0011_auto_20190831_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='enquiry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 31, 23, 35, 50, 260152)),
        ),
        migrations.AlterField(
            model_name='quest',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='entry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 31, 23, 35, 50, 260152)),
        ),
    ]
